SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
# SCREEN_WIDTH = 720
# SCREEN_HEIGHT = 480

SYS_FONT_NAME = 'ariel'
FONT_NAME = "resources/fonts/GOT.otf"
BIG_FONT_SIZE = 72

PRIMARY_COLOR = "#5C4B51"
SECONDARY_COLOR = "#F2EBBF"